influunt-app/.jshintrc, influunt-app/app/scripts/app.js, influunt-app/app/scripts/controllers/about.js, influunt-app/app/scripts/controllers/main.js, influunt-app/gulpfile.js, influunt-app/test/karma.conf.js, influunt-app/test/spec/controllers/about.js
* Escolha das regras de avaliação relevantes de qualidade de código javascript no codacy;
* Correção das questões já avaliadas pelo codacy;
* Atualização do .jshintrc, para alerta das regras de qualidade do codacy que estão quebradas (notificação de qualidade local);
=> Fixes codacy issues

influunt-app/.gitignore, influunt-app/app/index.html, influunt-app/app/json/locales/angular-locale_pt-br.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/main.css, influunt-app/app/styles/main.scss, influunt-app/app/styles/style.css
Remove os links (css's) da página index e os adiciona na lista do sass. Isto é necesário porque o processo de geração de buid do gulp não consegue encontrar os arquivos da mesma forma que o index o faz.
=> fixes build assets

influunt-app/app/styles/main.css, influunt-app/app/styles/main.scss, influunt-app/app/views/controladores/wizard/aneis.html
=> fix html/css aneis sidebar

.travis.yml, influunt-app/gulpfile.js
parametriza o ambiente do build gerado
=> parametriza o ambiente do build gerado

influunt-api/app/json/serializers/EstagioSerializer.java, influunt-api/app/models/Anel.java, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorDadosBasicosTest.java, influunt-api/test/models/ControladorTest.java
=> revisao de salvar aneis #105

influunt-api/app/json/deserializers/AnelDeserializer.java, influunt-api/app/json/deserializers/EstagioDeserializer.java, influunt-api/app/json/serializers/AnelSerializer.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/Estagio.java, influunt-api/app/models/EstagioGrupoSemaforico.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorTest.java
=> Revisao Associacao #106

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/json/deserializers/AnelDeserializer.java, influunt-api/app/json/deserializers/ControladorDeserializer.java, influunt-api/app/json/serializers/GrupoSemaforicoSerializer.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorTest.java, influunt-api/test/models/ControladorVerdesConflitantesTest.java
=> Revisao Verdes Conflitantes #107

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/directives/wizard-steps.js, influunt-app/test/spec/controllers/controladores.js
* Cria pré-condições para acessar determinado passo do wizard. Esta implementação deverá impedir, por exemplo, que um usuário acesse a tela de aneis sem ter configurado os dados básicos do anel.
=> 103 pre condicoes

influunt-api/app/checks/Erro.java, influunt-api/app/checks/InfluuntValidator.java
=> refactoring classe Erro #189

influunt-app/app/scripts/controllers/controladores.js
Corrige o problema reportado na validação de verdes conflitantes #193
=> fixes #193 - corrige erro de validacao dos verdes conflitantes

influunt-app/app/index.html, influunt-app/app/scripts/filters/limites-list-to-string.js, influunt-app/app/scripts/filters/resource-list-to-string.js, influunt-app/app/views/areas/_coordenadas.html, influunt-app/app/views/areas/index.html, influunt-app/app/views/areas/show.html, influunt-app/app/views/fabricantes/_modelos.html, influunt-app/app/views/fabricantes/form.html, influunt-app/test/spec/filters/limites-list-to-string.js, influunt-app/test/spec/filters/resource-list-to-string.js
=> 169 coordenadas em areas

influunt-app/app/views/areas/_coordenadas.html, influunt-app/app/views/fabricantes/_modelos.html, influunt-app/app/views/fabricantes/form.html
corrige select da tela de fabricantes
=> corrige select da tela de fabricantes

influunt-app/app/scripts/directives/ichecks.js, influunt-app/app/views/controladores/wizard/aneis.html
seleciona automaticamente um anel ao ativar - controladores, tela de aneis
=> auto select anel

influunt-app/app/plugins/steps/jquery.steps.css, influunt-app/app/scripts/config.js, influunt-app/app/styles/influunt.css, influunt-app/app/views/controladores/wizard/estagios.html, influunt-app/app/views/controladores/wizard/wizard.html
=> Front-end page estagio

influunt-api/app/checks/ControladorTransicoesProibidasCheck.java, influunt-api/app/controllers/ControladoresController.java, influunt-api/app/json/deserializers/AnelDeserializer.java, influunt-api/app/json/deserializers/EstagioDeserializer.java, influunt-api/app/json/deserializers/TransicaoProibidaDeserializer.java, influunt-api/app/json/serializers/EstagioSerializer.java, influunt-api/app/json/serializers/TransicaoProibidaSerializer.java, influunt-api/app/models/Estagio.java, influunt-api/app/models/Transicao.java, influunt-api/app/models/TransicaoProibida.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/conf/routes, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorTest.java, influunt-api/test/models/ControladorTransicoesProibidasTest.java
=> Proibicao de Estagios #135

influunt-api/app/checks/ConformidadeNumeroDetectores.java, influunt-api/app/checks/ConformidadeNumeroDetectoresEstagios.java, influunt-api/app/checks/ConformidadeNumeroDetectoresEstagiosValidator.java, influunt-api/app/checks/ConformidadeNumeroDetectoresValidator.java, influunt-api/app/checks/ConformidadeNumeroEstagiosValidator.java, influunt-api/app/checks/ControladorAssociacaoDetectoresCheck.java, influunt-api/app/controllers/ControladoresController.java, influunt-api/app/json/deserializers/AnelDeserializer.java, influunt-api/app/json/deserializers/DetectorDeserializer.java, influunt-api/app/json/deserializers/EstagioDeserializer.java, influunt-api/app/json/deserializers/GrupoSemaforicoDeserializer.java, influunt-api/app/json/deserializers/TabelaEntreVerdesDeserializer.java, influunt-api/app/json/serializers/AnelSerializer.java, influunt-api/app/json/serializers/DetectorSerializer.java, influunt-api/app/json/serializers/EstagioSerializer.java, influunt-api/app/json/serializers/GrupoSemaforicoSerializer.java, influunt-api/app/json/serializers/TransicaoSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Detector.java, influunt-api/app/models/Estagio.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/conf/application.conf, influunt-api/conf/evolutions/default/1.sql, influunt-api/conf/routes, influunt-api/conf/test.conf, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorTest.java
=> 132 configuracao detectores

influunt-app/app/scripts/config.js, influunt-app/app/styles/influunt.css, influunt-app/app/views/controladores/wizard/criacao-planos.html
=> Página criacao de planos

influunt-api/app/models/Agrupamento.java, influunt-api/conf/evolutions/default/1.sql, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/views/agrupamentos/form.html, influunt-app/app/views/agrupamentos/index.html, influunt-app/app/views/agrupamentos/show.html
=> Incluir numero em agrupamentos

influunt-api/app/json/deserializers/GrupoSemaforicoDeserializer.java, influunt-api/app/json/serializers/GrupoSemaforicoSerializer.java, influunt-api/app/models/GrupoSemaforico.java
=> Implementacao fase vermelha

influunt-api/app/json/serializers/DetectorSerializer.java, influunt-api/app/json/serializers/PlanoSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Detector.java, influunt-api/app/models/Plano.java, influunt-api/test/models/ControladorPlanoTest.java
=> verificacao modo isolado

influunt-api/app/json/serializers/ControladorSerializer.java, influunt-api/app/utils/InfluuntRange.java, influunt-api/app/utils/RangeUtils.java, influunt-api/test/models/ControladorDadosBasicosTest.java
=> implementacao faixa de valores

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/plugins/dropzone/dropzone.js, influunt-app/app/plugins/steps/jquery.steps.css, influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/main.css, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/app/views/controladores/wizard/wizard.html
=> fix menu wizard

influunt-api/app/models/Anel.java, influunt-api/app/models/ConfiguracaoControlador.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/influunt_seed.sql, influunt-api/test/controllers/ConfiguracoesControladoresControllerTest.java, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorTabelaEntreVerdesTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores/entre-verdes.js, influunt-app/app/styles/influunt.css, influunt-app/app/views/configuracoes_controladores/form.html, influunt-app/app/views/configuracoes_controladores/show.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/app/views/controladores/wizard/entre-verdes.html
Limite de tabelas entre verdes na configuração do controlador
=> #233 - limite de tabelas entre verdes

influunt-app/app/styles/influunt.css, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html
=> fix tela de verdes conflitantes

influunt-app/app/styles/influunt.css, influunt-app/app/views/controladores/wizard/tabela-estagios-proibidos.html, influunt-app/app/views/controladores/wizard/tabela-verdes-conflitantes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html
=> fix tela de transicoes proibidas

influunt-app/app/plugins/dropzone/dropzone.css, influunt-app/app/styles/influunt.css, influunt-app/app/styles/main.css, influunt-app/app/styles/main.scss, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html
=> #246 - ajustes titulos e labels

influunt-app/app/views/controladores/wizard/associacao.html
=> corrige rotas de associacao

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/json/menus.json, influunt-app/app/views/cidades/index.html, influunt-app/app/views/controladores/wizard/entre-verdes.html
fixes #311 #283 #285 #286 #305
=> 311 fix ajustes visuais

influunt-api/app/checks/CidadesCheck.java, influunt-api/app/controllers/CidadesController.java, influunt-api/app/models/Cidade.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/test/controllers/CidadesControllerTest.java, influunt-app/app/views/cidades/form.html, influunt-app/features/cidades/crud_cidades.feature, influunt-app/features/step_definitions/cidades/crud_cidades.steps.js, influunt-app/features/support/page-objects/cidades.js, influunt-app/features/support/scripts/cidades/create_cidade_duplicada.sql
=> fix cadastro de cidade com o mesmo nome

influunt-app/app/views/usuarios/index.html
=> Tela usuarios

influunt-api/app/controllers/ImagensController.java, influunt-api/app/models/Imagem.java, influunt-api/conf/routes, influunt-api/influunt_seed.sql, influunt-api/test/controllers/ImagensControllerTest.java, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/styles/influunt.css, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/test/spec/directives/fake-dropzone-preview.js, influunt-app/test/spec/directives/influunt-dropzone.js
=> #312 - fix image upload + delete

influunt-api/app/controllers/AreasController.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/config.js, influunt-app/app/scripts/services/crud/breadcrumbs.js, influunt-app/app/views/areas/_coordenadas.html, influunt-app/app/views/areas/form.html, influunt-app/app/views/areas/index.html, influunt-app/app/views/areas/show.html, influunt-app/app/views/cidades/_areas.html, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html, influunt-app/app/views/coordenada/_coordenada.html, influunt-app/app/views/fabricantes/_modelos.html
fix #328 #330 #333 #337 #344 #345
=> 352 labels placeholders etc

influunt-api/app/controllers/UsuariosController.java, influunt-api/app/json/deserializers/UsuarioDeserialiazer.java, influunt-api/app/json/serializers/UsuarioSerializer.java, influunt-api/app/models/Usuario.java, influunt-api/app/security/DBAuthenticator.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/influunt_seed.sql, influunt-api/test/controllers/UsuariosControllerTest.java, influunt-app/app/scripts/controllers/usuarios.js, influunt-app/app/views/usuarios/index.html, influunt-app/test/spec/controllers/usuarios.js
=> 314 fix login

influunt-api/app/checks/AoMenosUmGrupoSemaforicoValidator.java, influunt-api/app/checks/ConformidadeDeNumeroDeDetectoresDePedestreValidator.java, influunt-api/app/checks/ConformidadeDeNumeroDeDetectoresVeicularValidator.java, influunt-api/app/checks/ConformidadeDeNumeroDeGruposSemaforicosValidator.java, influunt-api/app/checks/ConformidadeNumeroDetectoresValidator.java, influunt-api/app/checks/ControladorGruposSemaforicosCheck.java, influunt-api/app/controllers/ControladoresController.java, influunt-api/app/json/deserializers/AnelDeserializer.java, influunt-api/app/json/serializers/AnelSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/Detector.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/app/models/Transicao.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/conf/routes, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorDadosBasicosTest.java, influunt-api/test/models/ControladorGruposSemaforicosTest.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-api/test/models/ControladorTabelaEntreVerdesTest.java, influunt-api/test/models/ControladorTest.java, influunt-api/test/models/ControladorTransicoesProibidasTest.java, influunt-api/test/models/ControladorVerdesConflitantesTest.java
=> Remover grupo semaforico e detectores da tela de anel e adicionar criacao de grupo semaforico apos anel

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/json/deserializers/EstagioDeserializer.java, influunt-api/app/json/serializers/EstagioSerializer.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-api/test/models/ControladorTest.java, influunt-api/test/models/ControladorTransicoesProibidasTest.java, influunt-api/test/models/ControladorVerdesConflitantesTest.java
=> Allterar da ordem do wizard

influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html, influunt-app/app/views/controladores/wizard/wizard.html
=> alterar ordem do menu wizard na app

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/json/deserializers/ControladorDeserializer.java, influunt-api/app/json/serializers/ControladorSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/StatusControlador.java, influunt-api/app/utils/RangeUtils.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorDadosBasicosTest.java, influunt-app/app/views/controladores/index.html, influunt-app/test/spec/controllers/controladores.js
- Inclusão do Status do Controlador
- Somente permite a edição de controladores que o cadastro não foram finalizados.
=> Status nos controladores

influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/planos/criacao-planos.html, influunt-app/app/views/planos/header-buttons.html
=> Ajuste legenda planos

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/index.html, influunt-app/app/scripts/controllers/controladores/entre-verdes.js, influunt-app/app/scripts/controllers/controladores/verdes-conflitantes.js, influunt-app/app/styles/main.css, influunt-app/app/styles/main.scss, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html
PR anterior cancelado devido um texto de marcação esquecido no code. Já foi removido.
=> Front iss#361

influunt-app/app/index.html, influunt-app/app/styles/influunt.css, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html, influunt-app/bower.json
verdes conflitantes e Transições proibidas
=> fix#iss309 Rolagem horizontal

influunt-app/app/plugins/dropzone/basic.css, influunt-app/app/plugins/dropzone/dropzone.css, influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/styles/directives/dropzone.css, influunt-app/app/styles/directives/dropzone.scss, influunt-app/app/views/controladores/wizard/aneis.html
=> fix dropzone upload area

influunt-app/app/scripts/controllers/controladores/associacao.js, influunt-app/app/scripts/directives/influunt-knob.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/controladores/wizard/associacao.html
=> Fix associacao page

influunt-api/app/json/deserializers/AnelDeserializer.java, influunt-api/app/json/serializers/AnelSerializer.java, influunt-api/app/json/serializers/EnderecoSerializer.java, influunt-api/app/json/serializers/FabricanteSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/Endereco.java, influunt-api/build.sbt, influunt-api/conf/evolutions/default/1.sql, influunt-api/influunt_seed.sql, influunt-api/test/controllers/AgrupamentosControllerTest.java, influunt-api/test/controllers/HelpersControllerTest.java, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorDadosBasicosTest.java, influunt-api/test/models/ControladorTest.java, influunt-api/test/models/ControladorVerdesConflitantesTest.java, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/directives/helper-endereco.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html
=> 402 aneis enderecos

influunt-app/app/index.html, influunt-app/app/scripts/directives/influunt-knob.js, influunt-app/app/views/directives/influunt-knob.html
=> add percentual knob

influunt-app/app/json/env.json, influunt-app/app/styles/main.css, influunt-app/app/styles/main.scss, influunt-app/config/deploy.rb
Pequenos ajustes de deploy + correção de erro no `main.scss`
=> ajustes deploy

influunt-api/app/controllers/ImagensController.java, influunt-api/app/models/Imagem.java, influunt-api/build.sbt, influunt-api/conf/routes, influunt-api/test/controllers/ImagensControllerTest.java, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/filters/image-source.js
Gera um thumb de 150x150 para cada imagem.
Adiciona nova rota GET :id/:version para obter o thumb
=> generate thumbs

influunt-api/app/models/Estagio.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/test/models/ControladorAssociacoesTest.java
=> add validacao de verdes conflitantes durante a associacao

influunt-api/app/models/Estagio.java, influunt-api/app/models/GrupoSemaforico.java, influunt-app/app/scripts/controllers/controladores/associacao.js
=> fix associacao de grupo e remover transicoes quando e proibida

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/plugins/diagrama-intervalos.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/directives/influunt-knob.js, influunt-app/app/scripts/directives/vis.js, influunt-app/app/scripts/services/validacoes/valida-transicao.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/styles/influunt/plano.css, influunt-app/app/styles/influunt/plano.scss, influunt-app/app/views/planos/criacao-planos.html, influunt-app/app/views/planos/opcoes-inferior.html, influunt-app/app/views/planos/opcoes-lateral.html, influunt-app/app/views/planos/tabela-planos.html, influunt-app/test/spec/filters/estagio-fora-sequencia.js, influunt-app/test/spec/services/validacoes/valida-transicao.js
Revisão da tela de planos para o novo formato de objeto.
=> 423 revisar planos

influunt-api/app/controllers/UsuariosController.java, influunt-api/app/json/deserializers/UsuarioDeserialiazer.java, influunt-api/app/json/serializers/AreaSerializer.java, influunt-api/app/json/serializers/UsuarioSerializer.java, influunt-app/app/views/usuarios/show.html
=> fix erro ao criar novo usuario

influunt-api/app/utils/RangeUtils.java, influunt-app/app/scripts/directives/influunt-knob.js, influunt-app/app/views/controladores/wizard/associacao.html
=> fix monitoramento de tempo de permanencia de estagio

influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/styles/directives/dropzone.css, influunt-app/app/styles/directives/dropzone.scss
=> fix layout upload dropzone

influunt-app/app/plugins/dropzone/dropzone.css, influunt-app/app/styles/directives/dropzone.css, influunt-app/app/styles/directives/dropzone.scss, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/controladores/wizard/aneis.html
Diminuir tamanho do uploader e imagens em aneis
=> fix#iss446

influunt-app/app/plugins/uiTabs/ui.tabs.overflowResize.css, influunt-app/app/styles/directives/influunt-tabs.css, influunt-app/app/styles/directives/influunt-tabs.scss, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html
- Review CSS, quebra de layout em 1024px;
- Aumento da área de clique das tabs;
- Imagens de estágios quebrando em entre-verdes;
=> combo issues #441 #434 #455

influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/plugins/catShow/catShow.js, influunt-app/app/scripts/config.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/controladores/wizard/revisao.html, influunt-app/app/views/controladores/wizard/wizard.html
=> refatoração da tela de revisão

influunt-app/app/index.html, influunt-app/app/scripts/directives/go-to-top.js, influunt-app/app/views/common/footer.html, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html, influunt-app/test/spec/directives/go-to-top.js
Adicionada a função que rola a página para o topo, para demonstrar os alertas de erros.
=> Função rolar para topo

influunt-api/app/json/ControladorCustomDeserializer.java, influunt-api/app/json/ControladorCustomSerializer.java, influunt-api/app/models/EstagioPlano.java, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/views/planos/criacao-planos.html, influunt-app/app/views/planos/opcoes-inferior.html
=> salvar planos

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/plugins/diagrama-intervalos.js, influunt-app/app/scripts/controllers/horarios.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/services/validacoes/valida-transicao.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/styles/influunt/variables.scss, influunt-app/app/views/planos/criacao-planos.html, influunt-app/app/views/planos/tabela-planos.html, influunt-app/gulpfile.js, influunt-app/package.json, influunt-app/test/spec/controllers/controladores.js, influunt-app/test/spec/services/validacoes/valida-transicao.js
=> 466 revisar diagram intervalos

influunt-api/app/models/Agrupamento.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/EstagioPlano.java, influunt-api/app/models/Plano.java, influunt-api/app/utils/InfluuntUtils.java, influunt-api/test/models/ControladorPlanoTest.java
=> Adicionar agrupamento no plano - API

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/config.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/timeline/index.html
=> Página Histórico de alterações

influunt-app/app/styles/influunt.css, influunt-app/app/views/tabela_horarios/configuracao.html, influunt-app/app/views/tabela_horarios/tabelas.html, influunt-app/app/views/tabela_horarios/tabs-eventos.html
Pattern de cores, para a página "Tabela de Horários"
=> Tabela de Horários - Colors

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/views/controladores/index.html
=> link para tela de revisao

influunt-api/conf/evolutions/default/1.sql, influunt-app/features/controladores/wizard.feature, influunt-app/features/step_definitions/controladores/wizard.steps.js, influunt-app/features/support/page-objects/wizard_controlador.js, influunt-app/features/support/scripts/agrupamentos/create_agrupamento.sql, influunt-app/features/support/scripts/controladores/entidades_dados_basicos.sql, influunt-app/features/support/scripts/create_usuario.sql, influunt-app/features/support/scripts/fabricantes/create_fabricante.sql, influunt-app/features/support/scripts/modelos_controladores/create_modelo_controlador.sql, influunt-app/features/support/scripts/planos/controlador.sql, influunt-app/features/support/world.js, influunt-app/package.json
=> 508 revisar cucumber wizard

influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html
- Desabilita campos readonly ( firefox )
=> fix input disabled firefox

influunt-api/app/models/Anel.java, influunt-api/app/models/Estagio.java, influunt-api/app/models/EstagioPlano.java, influunt-api/app/models/GrupoSemaforicoPlano.java, influunt-api/app/models/Plano.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/test/models/ControladorAneisTest.java, influunt-api/test/models/ControladorGruposSemaforicosTest.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-api/test/models/ControladorTestUtil.java, influunt-api/test/models/ControladorVerdesConflitantesTest.java, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/directives/vis.js
=> Validar tempo verde seguranca

influunt-app/app/plugins/diagrama-intervalos.js
=> Cor diferente para tempos nao utilizados

influunt-app/features/controladores/wizard.feature, influunt-app/features/step_definitions/controladores/wizard.steps.js, influunt-app/features/support/page-objects/wizard_controlador.js, influunt-app/features/support/world.js
=> Realizando reload na tela para remover os erros da tela

influunt-app/app/scripts/controllers/controladores/configuracao-grupos.js, influunt-app/app/views/controladores/wizard/configuracao-grupo.html
=> 548 fase vermelha apagada

influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/styles/directives/dropzone.css, influunt-app/app/styles/directives/dropzone.scss, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/test/spec/directives/influunt-dropzone.js
Obs: É preciso ajustar para salvar o croqui no local correto, está com a mesma configuração do estágio.
=> Upload de croqui

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/features/controladores/wizard.feature, influunt-app/features/step_definitions/controladores/wizard.steps.js, influunt-app/features/step_definitions/crud.steps.js, influunt-app/features/support/page-objects/crud.js, influunt-app/features/support/page-objects/wizard_controlador.js, influunt-app/features/support/world.js, influunt-app/test/spec/controllers/controladores/aneis.js
=> 566 dados do anel dados basicos

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/features/support/scripts/controladores/entidades_dados_basicos.sql
=> 637 bug no form aneis

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/plugins/uiTabs/ui.tabs.overflowResize.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/scripts/directives/influunt-tabs.js, influunt-app/app/views/directives/influunt-tabs/_tab.html
Ajustes do PR que ficaram para trás.
=> ajustes PR

influunt-api/app/json/ControladorCustomDeserializer.java, influunt-api/app/json/ControladorCustomSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/GrupoSemaforico.java, influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/configuracao-grupos.js, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/scripts/filters/nome-endereco.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/test/spec/controllers/controladores/configuracao-grupos.js, influunt-app/test/spec/controllers/controladores/dados-basicos.js, influunt-app/test/spec/filters/nome-endereco.js
- quebra de endereco em dados básicos
aneis -> voltar sem salvar
- Endereco de aneis não aparecia no mapa de aneis
- digest already in progress em enderecos, ao salvar aneis;
- Croqui não funcionava
- Apagar grupos semaforicos em configuracao de grupos
=> 643 apgar grupos semaforicos

influunt-api/app/json/ControladorCustomDeserializer.java, influunt-api/app/json/ControladorCustomSerializer.java, influunt-api/app/models/EstagioGrupoSemaforico.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorTabelaHorarioTest.java, influunt-api/test/models/ControladorTestUtil.java, influunt-app/test/spec/directives/ichecks.js
OBS: a issue #673 foi criada para resolver o teste desta tarefa.
=> Reassociar estagios x grupos semafóricos

influunt-app/app/scripts/controllers/controladores/associacao-detectores.js, influunt-app/app/scripts/controllers/controladores/verdes-conflitantes.js, influunt-app/app/scripts/services/auth-interceptor.js
fixes jshints
fix #628
fix #567
=> 628 mensagem validacao detectores

influunt-api/app/controllers/EventosController.java, influunt-api/app/controllers/TabelaHorariosController.java, influunt-api/app/helpers/ControladorUtil.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/conf/evolutions/default/1.sql, influunt-api/conf/routes, influunt-api/test/controllers/AbstractInfluuntControladorTest.java, influunt-api/test/controllers/ControladoresControllerTest.java, influunt-api/test/controllers/DetectoresControllerTest.java, influunt-api/test/controllers/EstagiosControllerTest.java, influunt-api/test/controllers/EventosControllerTest.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/tabela-horarios.js
=> remover evento da tabela horaria

influunt-api/app/controllers/PlanosController.java, influunt-api/app/helpers/ControladorUtil.java, influunt-api/app/json/ControladorCustomSerializer.java, influunt-api/app/models/Anel.java, influunt-api/app/models/Controlador.java, influunt-api/app/models/ControladorFisico.java, influunt-api/app/models/Estagio.java, influunt-api/app/models/GrupoSemaforico.java, influunt-api/conf/routes, influunt-api/test/controllers/PlanosControllerTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/directives/vis.js
- apagar planos
- tempo errado no diagrama de intervalos desativado
- erro ao trocar de anel na tela de planos
- plano copiado não é salvo
=> Apagar planos + vários ajustes

influunt-api/app/controllers/TabelaHorariosController.java, influunt-api/conf/routes, influunt-api/test/controllers/ControladoresControllerTest.java, influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/app/views/tabela_horarios/configuracao.html
=> cancelar edicao tabela horaria

influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/views/controladores/index.html
=> fix mostrar botao ativar

influunt-api/conf/evolutions/default/1.sql, influunt-app/app/scripts/directives/influunt-map.js
=> HOTFIX marker mapa

influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/associacao-detectores.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/controllers/status.js, influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/app/scripts/directives/helper-endereco.js, influunt-app/app/scripts/filters/influunt-date.js, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/features/step_definitions/cidades/crud_cidades.steps.js, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/support/page-objects/wizard_controlador.js, influunt-app/test/helpers/_main_spec_helper.js, influunt-app/test/spec/directives/fake-dropzone-preview.js, influunt-app/test/spec/directives/go-to-top.js, influunt-app/test/spec/directives/helper-endereco.js, influunt-app/test/spec/directives/tooltip.js, influunt-app/test/spec/directives/vis.js, influunt-app/test/spec/filters/nome-endereco.js, influunt-app/test/spec/services/handle-validations.js
fixes #736 and some codacy issues
=> 736 validar dados detectores

influunt-api/app/controllers/SecurityController.java, influunt-api/app/controllers/UsuariosController.java, influunt-api/app/security/AllowAllAuthenticator.java, influunt-api/app/security/Authenticator.java, influunt-api/app/security/DBAuthenticator.java, influunt-api/conf/evolutions/default/2.sql, influunt-api/conf/routes, influunt-api/modules/influunt-core/app/models/Sessao.java, influunt-api/test/TestAuthenticator.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/config.js, influunt-app/app/scripts/controllers/concerns/crud.js, influunt-app/app/scripts/controllers/main.js, influunt-app/app/scripts/controllers/usuarios.js, influunt-app/app/scripts/filters/influunt-date.js, influunt-app/app/views/usuarios/access_log.html, influunt-app/app/views/usuarios/index.html, influunt-app/test/spec/controllers/main.js
=> 666 log acesso

influunt-api/conf/routes, influunt-api/modules/influunt-core/app/models/Detector.java, influunt-api/modules/influunt-core/app/utils/RangeUtils.java, influunt-api/test/integracao/BasicMQTTTest.java, influunt-api/test/integracao/ConexaoTest.java, influunt-api/test/integracao/EnvioConfiguracaoTest.java, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/associacao-detectores.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/features/controladores/planos.feature, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/support/scripts/planos/controlador.sql, influunt-app/test/spec/controllers/controladores/aneis.js
Bugs Resolvidos 
3   - Resolvi
16 - Resolvi
18 - Resolvi
32 - Resolvi
13 - Resolvi
22 - Resolvi
Bugs que já estavam resolvido no staging 
1   - Resolvida em staging 
5   - Resolvida em staging
15 - Resolvida em staging
17 - Revolvida em staging
20 - Resolvida em staging 
27 - Resolvida em staging
29 - Resolvida em staging 
30 - Resolvida em staging
=> Correções da Listagem enviada pelo cliente Terceiro modulo

influunt-api/conf/capistrano/no_git_strategy.rb, influunt-app/app/index.html
=> Hotfix Deploy

influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/associacao.js, influunt-app/app/scripts/controllers/controladores/atraso-de-grupo.js, influunt-app/app/scripts/controllers/controladores/transicoes-proibidas.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/atraso-de-grupo.html, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html
Solução da lista número 10 - Issue #837
=> Bugs clientes 3

influunt-api/app/controllers/ControladoresController.java, influunt-api/conf/routes, influunt-api/modules/influunt-core/app/json/ControladorCustomSerializer.java, influunt-app/app/scripts/controllers/controladores/mapa.js
corrige os mapas para os ajustes atuais do staging
=> ajuste de mapas ao staging atual

influunt-app/app/plugins/influunt/diagrama-intervalos.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/views/planos/criacao-planos.html
#813  Correção do bug encontrado por Luciano
=> 813 bug planos errors

influunt-app/.jshintrc, influunt-app/app/scripts/controllers/main.js, influunt-app/app/scripts/controllers/subareas.js, influunt-app/app/scripts/controllers/usuarios.js, influunt-app/app/scripts/services/blockui-interceptor.js
fixes loading de controladores_offline/online em dashboard
=> Hotfix loading

influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html
Resolve os problemas:
- remover croqui antes de salvar o anel (linha 18)
- salvar dados básicos sem endereço (linha 5)
=> fixes croqui / dados básicos

influunt-app/app/views/main.html
=> voltar widgets

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/concerns/confirmacao-nada-ha-preencher.js, influunt-app/app/scripts/controllers/controladores/entre-verdes.js, influunt-app/app/views/controladores/wizard/entre-verdes.html
Corrige os problemas:
- confirmação não funciona direito (linha 24)
- combo aparece desmarcado ao voltar no anel (linha 25)
=> confirmacao entre verdes

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/utils/InfluuntQueryBuilder.java, influunt-api/conf/application.conf, influunt-api/test/seguranca/AutorizacaoTest.java, influunt-app/app/index.html, influunt-app/app/scripts/controllers/concerns/crud.js, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/directives/pesquisa-lateral.js, influunt-app/app/scripts/services/status_controlador.js, influunt-app/app/views/controladores/index.html, influunt-app/app/views/directives/pesquisa-lateral/pesquisa-lateral.html, influunt-app/app/views/directives/pesquisa-lateral/select.html, influunt-app/test/spec/controllers/controladores.js, influunt-app/test/spec/services/status_controlador.js
=> 39 filtro controladores

influunt-api/app/utils/InfluuntQueryBuilder.java
=> fix filtro de auditoria

influunt-app/app/scripts/controllers/controladores/associacao-detectores.js, influunt-app/app/scripts/controllers/controladores/revisao.js, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/directives/influunt-revisao/_aneis.html, influunt-app/test/spec/controllers/controladores/associacao-detectores.js
Resolve bug "No cadastra detector o total disponivel para cadastro, esta sendo calculado por controlador e deveria ser feita por anel"
=> calculando quantidade de detectores por anel

influunt-app/app/scripts/controllers/planos.js
Corrige o bug na linha 37 da planilha:
> Quando tem mais de uma plano no anel e ocorre o erro no plano que é diferente do Plano 1, a mensagem não aparecer dentro do plano que ocorreu o erro.
=> fix erros planos

influunt-api/app/controllers/ImagensController.java, influunt-api/test/controllers/ImagensControllerTest.java, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/test/spec/controllers/controladores/aneis.js
Corrige o bug da linha 19 da planilha:
>Adicionei 3 estagios no anel 1 e 3 no anel dois. ficou 5 no 1 e 1 no dois
=> fix dropzone in slow connections

.travis.yml, influunt-api/conf/logback.xml, influunt-api/project/build.properties, influunt-api/project/plugins.sbt, influunt-app/app/scripts/filters/influunt-time.js, influunt-app/app/views/agrupamentos/show.html, influunt-app/app/views/main.html
=> fix pataquada :disappointed: :bomb:

influunt-api/conf/evolutions/default/6.sql
=> inclusao do sql para a tabela de intervalos

influunt-app/app/scripts/controllers/concerns/crud.js
=> fix filtro de controladores

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/helpers/ControladorUtil.java, influunt-api/app/services/ControladorService.java, influunt-api/app/utils/InfluuntQueryBuilder.java, influunt-api/conf/evolutions/default/7.sql, influunt-api/conf/evolutions/default/8.sql, influunt-api/conf/routes, influunt-api/modules/influunt-core/app/json/ControladorCustomSerializer.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/modules/influunt-core/app/models/StatusVersao.java, influunt-api/modules/influunt-core/app/models/VersaoControlador.java, influunt-api/modules/influunt-core/app/models/VersaoPlano.java, influunt-api/modules/influunt-core/app/models/VersaoTabelaHoraria.java, influunt-api/test/controllers/ControladoresControllerTest.java, influunt-api/test/models/ControladorAssociacaoDetectoresTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/views/controladores/index.html, influunt-app/app/views/controladores/show.html, influunt-app/app/views/controladores/wizard/revisao.html, influunt-app/app/views/planos/criacao-planos.html
=> revisao dos botoes editar

influunt-api/modules/influunt-core/app/json/ControladorCustomSerializer.java
=> fixes #1004 dados duplicados

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/controllers/EstagiosController.java, influunt-api/conf/routes, influunt-api/influunt_seed.sql, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/test/controllers/EstagiosControllerTest.java, influunt-app/app/index.html, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/associacao.js, influunt-app/app/scripts/controllers/controladores/configuracao-grupos.js, influunt-app/app/scripts/controllers/controladores/transicoes-proibidas.js, influunt-app/app/scripts/services/remover-planos-tabelas-horarias.js, influunt-app/test/spec/controllers/controladores/aneis.js, influunt-app/test/spec/controllers/controladores/configuracao-grupos.js, influunt-app/test/spec/services/remover-planos-tabelas-horarias.js
=> remover planos e tabelas horarios quando necessario

influunt-app/app/scripts/services/handle-validations.js, influunt-app/app/views/agrupamentos/form.html, influunt-app/test/spec/services/handle-validations.js
=> 998 cadastro agrupamento

influunt-api/app/utils/InfluuntQueryBuilder.java, influunt-app/app/scripts/controllers/auditorias.js, influunt-app/app/styles/directives/pesquisa-lateral.css, influunt-app/app/styles/directives/pesquisa-lateral.scss, influunt-app/app/styles/main.css, influunt-app/app/styles/main.scss, influunt-app/app/views/directives/pesquisa-lateral/data.html, influunt-app/app/views/directives/pesquisa-lateral/pesquisa-lateral.html
=> fixes #1026 - pesquisa auditorias

influunt-api/conf/evolutions/default/11.sql, influunt-api/modules/influunt-core/app/json/ControladorCustomDeserializer.java, influunt-api/modules/influunt-core/app/json/ControladorCustomSerializer.java, influunt-api/modules/influunt-core/app/models/Anel.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/services/planos/plano-service.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/planos/criacao-planos.html
=> configurar controle manual

influunt-api/app/controllers/SecurityController.java, influunt-app/app/scripts/controllers/login.js
=> fix envio de mail

influunt-app/app/index.html, influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/app/scripts/services/crud/influunt-alert.js
=> fix tabela horario

influunt-api/app/controllers/FaixasDeValoresController.java, influunt-api/modules/influunt-core/app/checks/FaixaDeValoresCheck.java, influunt-api/modules/influunt-core/app/models/FaixasDeValores.java, influunt-api/test/controllers/FaixaDeValoresControllerTest.java, influunt-app/app/scripts/controllers/faixas-de-valores.js, influunt-app/app/views/faixas_de_valores/form.html
=> validacao de faixa de valores

influunt-api/default-drop-all.sql, influunt-app/features/agrupamentos/crud_agrupamentos.feature, influunt-app/features/step_definitions/agrupamentos/crud_agrupamentos.steps.js, influunt-app/features/support/page-objects/agrupamentos.js
- Correções para a tela de agrupamentos
=> Fix cucumber

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/helpers/ControladorUtil.java, influunt-api/modules/influunt-core/app/models/Anel.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-app/app/index.html, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/services/crud/influunt-alert.js, influunt-app/app/scripts/services/planos/plano-service.js, influunt-app/app/scripts/services/util/objects.js, influunt-app/app/views/planos/criacao-planos.html, influunt-app/bower.json, influunt-app/test/helpers/planos/controlador-com-plano-exclusivo.js, influunt-app/test/spec/controllers/planos.js
Corrige:
- posição errada do erro no plano.
- erro ao entrar na tela de planos de um controlador "CONFIGURADO"
- slimscroll fênix
=> Fix posição erro plano

influunt-api/influunt_seed.sql, influunt-app/app/scripts/config.js, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/associacao-detectores.js, influunt-app/app/scripts/controllers/controladores/associacao.js, influunt-app/app/scripts/controllers/controladores/atraso-de-grupo.js, influunt-app/app/scripts/controllers/controladores/configuracao-grupos.js, influunt-app/app/scripts/controllers/controladores/entre-verdes.js, influunt-app/app/scripts/controllers/controladores/revisao.js, influunt-app/app/scripts/controllers/controladores/transicoes-proibidas.js, influunt-app/app/scripts/controllers/controladores/verdes-conflitantes.js, influunt-app/app/scripts/controllers/simulacao.js, influunt-app/app/scripts/directives/influunt-map.js, influunt-app/app/scripts/directives/influunt-revisao.js, influunt-app/app/scripts/services/assert-controlador.js, influunt-app/app/views/controladores/show.html, influunt-app/app/views/directives/influunt-revisao/_aneis.html, influunt-app/app/views/directives/influunt-revisao/_transicoes-proibidas.html, influunt-app/app/views/directives/influunt-revisao/edit-in-revisao.html, influunt-app/app/views/planos/criacao-planos.html, influunt-app/test/spec/controllers/controladores/associacao-detectores.js, influunt-app/test/spec/controllers/controladores/associacao.js, influunt-app/test/spec/controllers/controladores/transicoes-proibidas.js, influunt-app/test/spec/controllers/controladores/verdes-conflitantes.js, influunt-app/test/spec/services/assert-controlador.js
=> 886 usabilidade planos

influunt-app/.jshintrc, influunt-app/app/scripts/controllers/concerns/crud.js, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/revisao.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/filters/dia-da-semana.js, influunt-app/app/scripts/services/handle-validations.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/directives/influunt-revisao/_aneis.html, influunt-app/app/views/directives/influunt-revisao/_associacao.html, influunt-app/app/views/directives/influunt-revisao/_dados_basicos.html, influunt-app/app/views/directives/influunt-revisao/main.html
fixes #1066 
* fixes #1058 
* fixes #1059 
* fixes #1061 
* Corrige todos os jshints apresentados em `staging`
=> 1066 epic ajustes

influunt-api/modules/influunt-core/app/models/TransicaoProibida.java, influunt-api/test/models/ControladorTransicoesProibidasTest.java, influunt-app/app/scripts/controllers/controladores/transicoes-proibidas.js, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/test/spec/controllers/controladores/transicoes-proibidas.js
PR relativo às issues #1060 e #1062
=> Fix mensagem erro e validação transições proibidas

influunt-api/modules/influunt-core/app/models/Estagio.java, influunt-api/test/models/ControladorTransicoesProibidasTest.java, influunt-app/app/scripts/controllers/controladores/transicoes-proibidas.js, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/test/spec/controllers/controladores/transicoes-proibidas.js
Deve existir pelo menos uma transição válida para o estágio.
=> Transição Proibida

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/security/AppDynamicResourceHandler.java, influunt-api/influunt_seed.sql, influunt-api/modules/influunt-core/app/models/Usuario.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/services/status_controlador.js, influunt-app/app/views/controladores/index.html, influunt-app/app/views/directives/pesquisa-lateral/pesquisa-lateral.html, influunt-app/app/views/directives/pesquisa-lateral/select.html
=> fix busca por area

influunt-app/app/scripts/controllers/concerns/confirmacao-nada-ha-preencher.js, influunt-app/app/scripts/controllers/controladores/atraso-de-grupo.js, influunt-app/app/views/controladores/wizard/atraso-de-grupo.html
Quando entro em um anel e marco que não há nada a ser feito e troco de aba e posteriormente volto na aba onde marquei o combo não vem marcado.
=> Atraso de grupo

influunt-api/app/controllers/AreasController.java, influunt-api/app/helpers/ControladorHelper.java, influunt-api/modules/influunt-core/app/models/Perfil.java, influunt-api/test/seguranca/AutorizacaoTest.java, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/controllers/login.js, influunt-app/app/scripts/services/initializers/permissions.js, influunt-app/app/scripts/services/permissions-service.js, influunt-app/app/views/controladores/wizard/dados-basicos.html
Se eu tento avançar sem informar nenhum dado, aparece a mensagem de não autorizado.
Estou usando um usuário associado com um area. O ideia que é a area já estivesse preenchida e que o usuário não pudesse mudar.
=> Não é possível sair da tela de dados básicos

influunt-app/app/views/tabela_horarios/configuracao.html
=> fixes #1105 :unamused:

influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html
=> fixes #1102

influunt-api/app/templates/recuperarSenha.html, influunt-api/app/utils/InfluuntEmailService.java, influunt-api/build.sbt
=> fix envio de email

influunt-api/app/controllers/CidadesController.java, influunt-api/app/controllers/SubareasController.java, influunt-api/influunt_seed.sql, influunt-api/test/seguranca/AutorizacaoTest.java, influunt-app/app/scripts/config.js, influunt-app/app/scripts/controllers/login.js, influunt-app/app/scripts/controllers/perfis.js, influunt-app/app/scripts/services/initializers/permissions.js, influunt-app/app/scripts/services/permissions-service.js, influunt-app/test/spec/controllers/controladores/transicoes-proibidas.js, influunt-app/test/spec/controllers/login.js, influunt-app/test/spec/directives/influunt-map.js, influunt-app/test/spec/services/modo-operacao.js, influunt-app/test/spec/services/permissions-service.js
Corrige as issues #1097 e #1110.
=> 1097/1110 - fix permissões por área + cache

influunt-api/app/controllers/ImagensController.java, influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/directives/fake-dropzone-preview.js, influunt-app/app/scripts/directives/influunt-dropzone.js, influunt-app/app/scripts/services/permissions-service.js, influunt-app/app/scripts/services/util/dropzone.js, influunt-app/app/styles/directives/dropzone.css, influunt-app/app/styles/directives/dropzone.scss, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/test/spec/directives/fake-dropzone-preview.js, influunt-app/test/spec/directives/influunt-dropzone.js, influunt-app/test/spec/services/util/dropzone.js
fixes #1118 
* fixes #1083 
* fixes #1099 
* Corrige problemas do influunt-dropzone quando a API responde com um código de erro ao app.
=> 1118 fix dropzone

influunt-app/app/scripts/directives/influunt-map.js
=> fixes #1125

influunt-api/app/controllers/PlanosController.java, influunt-api/app/controllers/TabelaHorariosController.java, influunt-api/modules/influunt-core/app/json/ControladorCustomSerializer.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-app/app/scripts/controllers/concerns/confirmacao-nada-ha-preencher.js, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/views/controladores/index.html, influunt-app/features/support/scripts/create_usuario.sql
=> Fix status controlador (1106) e fix wizard transições proibidas (1126)

influunt-app/app/scripts/controllers/concerns/breadcrumbs.js, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/services/crud/breadcrumbs.js, influunt-app/app/views/common/breadcrumbs.html, influunt-app/test/spec/controllers/concerns/breadcrumbs.js, influunt-app/test/spec/services/crud/breadcrumbs.js
=> 1131 - fix breadcrumb endereço do anel

influunt-app/app/scripts/controllers/main.js, influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/app/scripts/directives/influunt-tabs.js, influunt-app/app/scripts/services/permissions-service.js, influunt-app/app/views/common/top_navigation.html, influunt-app/app/views/tabela_horarios/tabelas.html
=> 1149 menu cadastro

influunt-api/app/security/AppDynamicResourceHandler.java, influunt-app/app/scripts/config.js
Definimos que essa rota vai ficar liberada até encontrarmos uma solução melhor.
=> 1148 - fix login sem permissão de status controladores

influunt-app/app/scripts/controllers/planos.js, influunt-app/features/controladores/planos.feature, influunt-app/features/controladores/tabelas_horarias.feature, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/support/page-objects/planos.js
- Agora os cenários estão verificando os tempos corretamente no diagrama de intervalo, checando os erros em estágios e salvando uma configuração com 5 planos em cada anel com cada modo.
=> Aumento cobertura cucumber para Planos

influunt-api/influunt_seed.sql, influunt-app/app/views/perfis/index.html
=> hotfix permissões

influunt-app/features/controladores/tabelas_horarias.feature, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/step_definitions/controladores/tabelas_horarias.steps.js, influunt-app/features/step_definitions/controladores/wizard.steps.js, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/page-objects/planos.js, influunt-app/features/support/page-objects/tabelas_horarias.js, influunt-app/features/support/page-objects/wizard_controlador.js
- Testando vários eventos em uma tabela horária.
- Verificando o quadro de horário, se está marcando as cores corretamente.
- E algumas validações adicionadas.
=> Aumento cobertura cucumber para Tabela horária

influunt-api/conf/evolutions/default/15.sql, influunt-api/modules/influunt-core/app/json/ControladorCustomDeserializer.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/modules/influunt-core/app/models/Evento.java, influunt-api/modules/influunt-core/app/models/TabelaHorario.java, influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/features/controladores/planos.feature, influunt-app/features/controladores/tabelas_horarias.feature, influunt-app/features/controladores/wizard.feature, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/page-objects/planos.js, influunt-app/features/support/scripts/controladores/set_controlador_finalizado.sql, influunt-app/features/support/scripts/planos/controlador.sql, influunt-app/gulpfile.js, influunt-app/test/spec/controllers/tabela-horarios.js
Fixes #1168 (Botão de finalizar aparece sem tabela horária configurada)
=> fixes #1168 + app tests

influunt-app/app/index.html, influunt-app/app/scripts/controllers/controladores.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/verdes-conflitantes.js, influunt-app/app/scripts/controllers/faixas-de-valores.js, influunt-app/app/scripts/directives/wizard-footer.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/associacao-detectores.html, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/controladores/wizard/atraso-de-grupo.html, influunt-app/app/views/controladores/wizard/configuracao-grupo.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/app/views/controladores/wizard/entre-verdes.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/app/views/controladores/wizard/verdes-conflitantes.html, influunt-app/app/views/directives/wizard-footer.html, influunt-app/test/spec/controllers/controladores.js
fixes #1150 (Mensagem de salvo com sucesso para faixas de valores)
fixes #916 (diretiva para botões de footer do wizard + mensagens de salvo com sucesso para salvar e permanecer na tela)
=> fixes some issues

influunt-app/app/scripts/controllers/concerns/historico.js, influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/app/views/tabela_horarios/tabs-eventos.html, influunt-app/test/spec/controllers/tabela-horarios.js
* closes #1142 (Colovar badge de erro nas tabs de tipos de eventos em tabelas horárias)
* Corrige posicionamento de badges de erros de eventos quando há mais de uma versão.
=> closes #1142 and fixes some issues

influunt-api/modules/influunt-core/app/models/GrupoSemaforico.java, influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/test/models/ControladorAssociacoesTest.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-api/test/models/ControladorVerdesConflitantesTest.java, influunt-app/.jshintrc, influunt-app/app/index.html, influunt-app/app/scripts/controllers/controladores/associacao.js, influunt-app/app/scripts/controllers/login.js, influunt-app/app/scripts/directives/check-browser.js, influunt-app/app/views/controladores/wizard/associacao.html, influunt-app/app/views/directives/check-browser.html, influunt-app/app/views/login/recuperar_senha.html, influunt-app/app/views/login/redefinir_senha.html, influunt-app/app/views/login/signin.html, influunt-app/app/views/planos/criacao-planos.html
* fixes #1221 -> Epic de ajustes
* fixes #1212 -> Associação Grupo x Estágios: Conssitência de "todos os GS precisam estar associados a estágios"
* fixes #1154 -> Ajustes planos: 
* fixes #1213 -> Fixes mensagem de browser imcompativel para IE
=> 1221 epic ajustes

influunt-api/modules/influunt-core/app/models/Agrupamento.java, influunt-api/test/controllers/AgrupamentosControllerTest.java, influunt-app/app/scripts/controllers/concerns/crud.js, influunt-app/app/views/agrupamentos/form.html
closes #1161 - Validacao agrupamento - aneis devem ser da mesma area
=> closes #1161 - Validacao agrupamento - aneis devem ser da mesma area

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/views/controladores/wizard/tabela-estagios-proibidos.html, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/features/support/page-objects/wizard_controlador.js
closes #1211  - Inverter posição de/para na tabela de transições proibidas (+cucumber ok)
=> closes #1211 - inverter posicao de/para de transicoes proibidas

influunt-api/modules/influunt-core/app/engine/GerenciadorDeEstagios.java, influunt-api/test/execucao/GerenciadorDeEstagiosTest.java, influunt-api/test/integracao/ControladorHelper.java, influunt-api/test/integracao/JsonTest.java
=> add geracao de intervalo estagio unico

influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/directives/influunt-faixa-valores.js, influunt-app/app/views/directives/influunt-faixa-valores.html, influunt-app/app/views/faixas_de_valores/form.html, influunt-app/test/spec/directives/influunt-faixa-valores.js
=> ajustes campos faixa de valores

influunt-api/modules/influunt-core/app/models/Estagio.java, influunt-api/test/models/ControladorAssociacoesTest.java
=> add validacao de tempo de permanencia de estagio

influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html
closes #1264 - Alteração da posição dos campos de lat e lng para o final de todas as áreas de endereços.
=> 1264 posicao latlng

influunt-api/modules/influunt-core/app/models/EstagioPlano.java, influunt-api/test/execucao/GerenciadorDeEstagiosTest.java, influunt-api/test/integracao/ControladorHelper.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-api/test/models/ControladorTestUtil.java, influunt-app/app/scripts/controllers/planos.js, influunt-app/test/spec/controllers/planos.js
close #1292
close #1262 
close #1257 
close #1263 
close #1269
=> add validacoes planos

influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-app/app/scripts/controllers/planos.js, influunt-app/test/spec/controllers/planos.js
=> Validação número de estágios em plano modo manual

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/tabela-horarios.js
- fixes #1280 - cores erradas na tabela horaria
- fixes #1255 erro ao visualizar diagrama de intervalos de plano não configurado
- fixes #1254 diagrama de intervalos errado
=> 1295 epic correcoes tabelas horarias

influunt-app/app/json/menus.json, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/features/perfis/perfis.feature, influunt-app/test/spec/controllers/controladores/aneis.js
fixes #1246 -> Remover dados de anel quando for deletado;
fixes #1281 -> Remoção das auditorias do menu
=> fixes 1246 and fixes #1281

influunt-app/app/scripts/directives/influunt-knob.js, influunt-app/app/views/planos/opcoes-inferior.html
fixes #1326 -> Extensão de verde em décimos de segundo.
=> fixes #1326 - extensao de verde deve suportar casas decimais

influunt-api/modules/influunt-core/app/engine/eventos/DetectorVeicularHandle.java, influunt-api/test/execucao/GerenciadorDeEstagiosTest.java
=> add calculo de extensao de verde

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/views/planos/opcoes-inferior.html, influunt-app/test/spec/controllers/planos.js
fixes #1355 - bug estágio que recebe tempo do estágio dispensável
=> fixes #1355 - bug estágio que recebe tempo do estágio dispensável

influunt-api/app/controllers/ControladoresController.java, influunt-api/modules/influunt-core/app/checks/ControladorFinalizaConfiguracaoCheck.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/test/controllers/ControladoresControllerTest.java, influunt-app/app/scripts/controllers/controladores.js
closes #1310 - obrigar SMEE ao finalizar controlador
=> closes #1310 - obrigar SMEE ao finalizar controlador

influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/directives/ichecks.js, influunt-app/app/scripts/services/planos/plano-service.js, influunt-app/test/helpers/planos/controlador-com-varios-aneis.js, influunt-app/test/spec/controllers/planos.js, influunt-app/test/spec/services/planos/plano-service.js
=> fix ajustes finos planos

influunt-api/app/controllers/ControladoresController.java, influunt-api/default-drop-all.sql, influunt-api/influunt_seed.sql, influunt-app/app/json/i18n-pt-br.json, influunt-app/features/agrupamentos/crud_agrupamentos.feature, influunt-app/features/controladores/planos.feature, influunt-app/features/mapas/filter_mapas.feature, influunt-app/features/mapas/mapas.feature, influunt-app/features/step_definitions/agrupamentos/crud_agrupamentos.steps.js, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/step_definitions/controladores/resumo_controladores.steps.js, influunt-app/features/step_definitions/mapas/mapas.steps.js, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/agrupamentos.js, influunt-app/features/support/page-objects/mapas.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/scripts/controladores/controladores.sql, influunt-app/features/support/scripts/controladores/controladores_finalizados.sql, influunt-app/features/support/scripts/planos/controlador.sql, influunt-app/features/support/world.js
Cucumber para o mapa, mais fixes
=> Cucumber mapa

influunt-app/app/scripts/controllers/controladores/transicoes-proibidas.js, influunt-app/app/views/controladores/wizard/transicoes-proibidas.html, influunt-app/features/controladores/editar_controladores.feature, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/page-objects/wizard_controlador.js
Correção da issue #1391, e teste para contemplar a issue #1393
=> 1391 bug transicao proibida

influunt-api/app/controllers/FabricantesController.java, influunt-api/modules/influunt-core/app/models/ModeloControlador.java, influunt-api/test/controllers/FabricantesControllerTest.java, influunt-api/test/models/ControladorTestUtil.java, influunt-app/app/scripts/controllers/concerns/crud.js, influunt-app/features/fabricantes/crud_fabricantes.feature, influunt-app/features/step_definitions/fabricantes/crud_fabricantes.steps.js, influunt-app/test/spec/controllers/concerns/crud.js
fixes #1353 Erro ao excluir um fabricante com modelo associado a um controlador.
=> fixes #1353

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/controllers/PlanosController.java, influunt-api/modules/influunt-core/app/json/ControladorCustomDeserializer.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/modules/influunt-core/app/models/EstagioPlano.java, influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-api/test/models/ControladorTabelaHorarioTest.java, influunt-app/app/plugins/influunt/diagrama-intervalos.js, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/services/diagrama-intervalos/gera-dados.js, influunt-app/app/scripts/services/planos/plano-service.js, influunt-app/app/views/planos/criacao-planos.html, influunt-app/test/spec/controllers/planos.js
=> 1388 - remover estágios planos

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/controllers/SubareasController.java, influunt-api/conf/routes, influunt-api/modules/influunt-core/app/models/Evento.java, influunt-api/test/controllers/SubareasControllerTest.java, influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/concerns/crud.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/controllers/subareas.js, influunt-app/app/scripts/filters/resource-list-to-string.js, influunt-app/app/scripts/filters/status-controlador.js, influunt-app/app/styles/influunt.css, influunt-app/app/styles/influunt.scss, influunt-app/app/views/agrupamentos/form.html, influunt-app/app/views/controladores/index.html, influunt-app/app/views/subareas/form.html, influunt-app/app/views/subareas/show.html, influunt-app/test/spec/controllers/subareas.js, influunt-app/test/spec/filters/status-controlador.js
closes #1411 Correções/sugestões do PDF (10/11/2016)
=> 1411 epic de correcoes

influunt-api/app/controllers/PlanosController.java, influunt-api/app/controllers/TabelaHorariosController.java, influunt-api/conf/evolutions/default/20.sql, influunt-api/modules/influunt-core/app/models/VersaoControlador.java, influunt-api/modules/influunt-core/app/models/VersaoPlano.java, influunt-api/modules/influunt-core/app/models/VersaoTabelaHoraria.java, influunt-app/app/views/controladores/timeline.html, influunt-app/app/views/directives/influunt-modal-timeline.html, influunt-app/features/controladores/historico_controlador.feature, influunt-app/features/step_definitions/controladores/historicos.steps.js, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/historico.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/scripts/controladores/controladores.sql, influunt-app/features/support/scripts/controladores/controladores_finalizados.sql, influunt-app/features/support/scripts/controladores/controladores_por_areas.sql, influunt-app/features/support/scripts/controladores/plano_controlador.sql, influunt-app/features/support/scripts/controladores/tabela_horaria_controlador.sql, influunt-app/features/support/scripts/create_usuario.sql, influunt-app/features/support/scripts/planos/controlador.sql
Fix #1094 
Fix #1128 
Fix #1407 
Mais cucumber
=> 1128 historico de versoes

influunt-app/features/agrupamentos/crud_agrupamentos.feature, influunt-app/features/controladores/planos.feature, influunt-app/features/step_definitions/agrupamentos/crud_agrupamentos.steps.js, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/support/page-objects/agrupamentos.js, influunt-app/features/support/page-objects/planos.js
#1417  Problema ja foi solucionado. Realizei teste de aceitação no campo, e mais algumas melhorias no agrupamento
=> 1417 bug defasagem

influunt-app/app/index.html, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/app.js, influunt-app/app/scripts/config.js, influunt-app/app/scripts/controllers/main.js, influunt-app/app/scripts/services/crud/influunt-alert.js, influunt-app/app/scripts/services/initializers/idle-config.js, influunt-app/app/views/common/content_top_navigation.html, influunt-app/app/views/common/modal-idle-warning.html, influunt-app/bower.json, influunt-app/gulpfile.js, influunt-app/test/karma.conf.js
closes #865 - finalizar sessao por tempo de inatividade
=> closes #865 - finalizar sessao por tempo de inatividade

influunt-api/modules/influunt-core/app/json/serializers/AgrupamentoSerializer.java, influunt-api/modules/influunt-core/app/status/AlarmesFalhasControlador.java, influunt-app/app/scripts/directives/influunt-map.js
hotfixes mapa em dados basicos
=> hotfixes mapa em dados basicos

influunt-api/influunt_seed.sql, influunt-api/modules/influunt-core/app/models/GrupoSemaforico.java, influunt-app/features/mapas/permissoes_mapa.feature, influunt-app/features/step_definitions/agrupamentos/crud_agrupamentos.steps.js, influunt-app/features/support/page-objects/agrupamentos.js, influunt-app/features/support/page-objects/mapas.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/scripts/create_usuario.sql
Correção dos cucumber mais permissão monitoramento status aneis
=> Fix cucumbers

.travis.yml, influunt-api/app/controllers/RelatoriosController.java, influunt-api/app/reports/ControladoresReportService.java, influunt-api/app/reports/PlanosReportService.java, influunt-api/app/security/Auditoria.java, influunt-api/conf/application.conf, influunt-api/influunt_seed.sql, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/filters/resource-to-string.js, influunt-app/app/views/controladores/show.html, influunt-app/app/views/relatorios/planos.html, influunt-app/test/spec/filters/resource-list-to-string.js, influunt-app/test/spec/filters/resource-to-string.js
Filtra os dados dos relatórios caso o usuário não seja root nem tenha permissão de visualizar todas as áreas.
=> 1493 - filtrar relatórios por área

influunt-api/app/views/report/controlador.scala.html, influunt-api/influunt_seed.sql, influunt-app/app/json/i18n-pt-br.json, influunt-app/features/relatorios/controlador.feature, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/scripts/create_usuario.sql, influunt-app/features/support/world.js
Fixes para o relatório do controlador
=> relatório controlador closes #1488

influunt-app/app/scripts/controllers/relatorios/relatorio-tabela-horaria.js, influunt-app/app/views/relatorios/tabelaHoraria.html, influunt-app/features/relatorios/relatorio_tabela_horaria.feature, influunt-app/features/step_definitions/areas/crud_areas.steps.js, influunt-app/features/step_definitions/relatorios/relatorios.steps.js, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/crud.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/page-objects/relatorios.js
- Fix #1495 
- Testes para o relátorio
=> Bug  relatório tabela horaria 

influunt-api/app/helpers/ControladorUtil.java, influunt-app/features/controladores/editar_planos.feature, influunt-app/features/step_definitions/controladores/planos.steps.js, influunt-app/features/support/page-objects/planos.js
=> 1519 fixes plano

influunt-api/modules/influunt-core/app/models/Estagio.java, influunt-api/test/models/ControladorAssociacoesTest.java
=> validacao tempo de verde demanda prioritaria

influunt-app/app/scripts/controllers/planos.js, influunt-app/features/controladores/planos.feature
closes #1521 bug ao limpar plano temporário
=> Fix bug ao limpar plano temporário

influunt-app/features/controladores/editar_planos.feature
@leonardoherbert Os testes não quebraram, porem realizei o específico para ele
=> Teste verde mínimo para estágio dispensável

influunt-app/app/scripts/controllers/tabela-horarios.js, influunt-app/features/controladores/tabelas_horarias.feature, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/objetos_comuns.js
=> Breadcrumb endereço controlador em tabela horária

influunt-app/app/scripts/controllers/login.js, influunt-app/features/login.feature, influunt-app/features/step_definitions/login.steps.js, influunt-app/features/step_definitions/shared.steps.js, influunt-app/features/support/page-objects/login.js, influunt-app/features/support/page-objects/objetos_comuns.js, influunt-app/features/support/world.js
=> Fix I18n recuperar senha

influunt-api/build.sbt, influunt-api/modules/influunt-central/app/server/Central.java, influunt-api/modules/influunt-central/app/server/conn/ServerActor.java, influunt-api/modules/influunt-core/app/engine/Motor.java, influunt-api/modules/influunt-core/app/engine/eventos/GerenciadorDeEventos.java, influunt-api/modules/influunt-core/app/logger/InfluuntLogger.java, influunt-api/modules/influunt-core/app/logger/TipoLog.java, influunt-api/modules/influunt-core/app/protocol/EtapaTransacao.java, influunt-api/modules/influunt-device/app/os72c/client/Client.java, influunt-api/modules/influunt-device/app/os72c/client/conn/ClientActor.java, influunt-api/modules/influunt-device/app/os72c/client/conn/DeviceMessageBroker.java, influunt-api/modules/influunt-device/app/os72c/client/device/DeviceActor.java, influunt-api/modules/influunt-device/app/os72c/client/handlers/TransacaoActorHandler.java, influunt-api/modules/influunt-device/app/os72c/client/handlers/TransacaoManagerActorHandler.java, influunt-api/modules/influunt-device/app/os72c/client/virtual/ControladorForm.java, influunt-api/modules/influunt-device/app/os72c/client/virtual/GenericPanelActionListener.java, influunt-api/test/execucao/gerenciadorEstagios/GerenciadorDeEstagiosDemandaPrioritariaTest.java, influunt-api/test/execucao/gerenciadorEstagios/GerenciadorDeEstagiosDispensavelTest.java, influunt-api/test/execucao/gerenciadorEstagios/GerenciadorDeEstagiosGeralTest.java, influunt-api/test/execucao/gerenciadorEstagios/GerenciadorDeEstagiosModoManualTest.java, influunt-api/test/integracao/BasicMQTTTest.java, influunt-api/test/integracao/JUnitRetry.java
Tornar o log mais humano
Envio de alertas de fechamento
=> Ajuste controlador virtual

influunt-api/app/views/report/controlador.scala.html
=> Fix relatório controlador PDF

influunt-api/app/controllers/monitoramento/MonitoramentoController.java, influunt-api/modules/influunt-core/app/status/StatusConexaoControlador.java, influunt-api/test/controllers/monitoramento/StatusConexaoTest.java, influunt-app/app/scripts/filters/nome-endereco.js
=> últimos 30 dias no status do controlador

influunt-api/app/controllers/simulacao/SimuladorController.java, influunt-api/conf/routes, influunt-app/app/scripts/controllers/simulacao.js, influunt-app/gulpfile.js, influunt-app/test/karma.conf.js, influunt-app/test/spec/controllers/simulacao.js
=> Gerenciar ciclo de vida do simulador

influunt-api/app/controllers/ControladoresController.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/modules/influunt-device/app/os72c/client/Client.java, influunt-api/modules/influunt-device/app/os72c/client/conn/ClientActor.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/views/impor_config/index.html, influunt-app/test/spec/controllers/simulacao.js
=> 1562 painel facilidades controlador offline

influunt-api/modules/influunt-device/app/os72c/client/virtual/ControladorForm.java
=> ajuste alarmes controlador

influunt-api/app/controllers/monitoramento/MonitoramentoController.java, influunt-api/app/reports/ControladoresReportService.java, influunt-api/modules/influunt-core/app/status/AlarmesFalhasControlador.java
=> Fix busca por falha em relatório de falhas

influunt-api/influunt_seed.sql, influunt-api/modules/influunt-core/app/logger/InfluuntLogger.java, influunt-app/app/views/controladores/mapa/acoes-anel.html, influunt-app/app/views/directives/alterar-status.html, influunt-app/app/views/directives/imposicoes/sincronizacao-form.html, influunt-app/app/views/impor_config/index.html, influunt-app/app/views/impor_config/modal-transacoes.html
=> Permissões painel de facilidades

influunt-api/app/controllers/PlanosController.java, influunt-api/app/controllers/TabelaHorariosController.java, influunt-api/modules/influunt-core/app/json/ControladorCustomDeserializer.java, influunt-api/modules/influunt-core/app/models/VersaoPlano.java, influunt-api/modules/influunt-core/app/models/VersaoTabelaHoraria.java, influunt-app/app/scripts/controllers/controladores.js
=> Melhoria mensagem de nova versão plano e tabela horária

influunt-api/modules/influunt-core/app/models/simulador/SimulacaoConfig.java, influunt-api/modules/influunt-core/app/models/simulador/parametros/ParametroSimulacao.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/plugins/influunt/visualizacao-simulador.js
closes #1573 -> alteração de labels do sistema.
closes #1645 -> troca de label do modo de operação no simulador.
=> 1645 ajustar modo operacao simulador

influunt-app/app/scripts/controllers/planos.js
closes #1646 -> limpar mensagens de validação quando o usuário alterar dados no plano
=> closes #1646

influunt-api/modules/influunt-device/app/os72c/client/Client.java, influunt-api/modules/influunt-device/app/os72c/client/conn/MQTTClientActor.java, influunt-api/modules/influunt-device/app/os72c/client/device/SerialDeviceJava.java, influunt-api/modules/influunt-device/app/os72c/client/handlers/ErroActorHandler.java, influunt-app/app/resources/controlador.conf, influunt-app/app/scripts/directives/influunt-modal-instalacao.js, influunt-app/app/views/directives/influunt-modal-instalacao.html
=> Ajustes arquivo de configuração do controlador

influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/controllers/main.js, influunt-app/app/scripts/directives/helper-endereco.js, influunt-app/app/scripts/services/crud/influunt-alert.js, influunt-app/app/scripts/services/paho-provider.js, influunt-app/app/views/controladores/wizard/dados-basicos.html
* Altera validação dos SMEE na tela de dados básicos: Um __"alert"__ será exibido sempre que houver uma alteração válida do número do SMEE. O usuário deverá confirmar que o endereço é do controlador correto. Caso não seja encontrado um registro no SMEE, o sistema deverá alertar o usuário;
* Reconexão do MQTT caso esta seja perdida ou não estabelecida desde o início da aplicação.
=> closes #1663

influunt-api/modules/influunt-core/app/models/Anel.java, influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/test/integracao/ControladorHelper.java, influunt-api/test/integracao/JsonTest.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-app/app/scripts/controllers/planos.js, influunt-app/app/scripts/services/planos/plano-service.js, influunt-app/app/views/planos/criacao-planos.html, influunt-app/package.json
closes #1653 -> Valida que todos os aneis tenham os mesmos planos ativados (exceto para os planos temporários).
=> closes #1653

influunt-api/influunt_seed.sql
Trocando "Painel de Facilidades" -> "Comandos da Central" nas descrições das permissões.
=> Ajustes nomes de permissoes

influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/test/integracao/EnvioConfiguracaoCompletaTest.java
=> remover os planos manuais da validacao de existir em todos os aneis

influunt-api/app/controllers/monitoramento/MonitoramentoController.java, influunt-api/app/reports/ControladoresReportService.java, influunt-api/modules/influunt-core/app/status/LogControlador.java, influunt-api/modules/influunt-core/app/status/StatusConexaoControlador.java, influunt-app/app/scripts/controllers/main.js, influunt-app/app/scripts/controllers/relatorios.js, influunt-app/app/scripts/services/blockui-interceptor.js, influunt-app/app/scripts/services/influunt-blockui.js, influunt-app/app/views/relatorios/logControladores.html
fixes #1696
fixes #1684
fixes #1674
=> ajustes ordenação + correção relatorio log + ajuste blockUI

influunt-app/app/scripts/services/status_controlador.js
=> Troca status "ativo" p/ "sincronizado" no index de controladores

influunt-api/app/reports/ControladoresReportService.java, influunt-api/app/reports/PlanosReportService.java, influunt-api/app/utils/InfluuntQueryBuilder.java, influunt-api/conf/application.conf, influunt-api/modules/influunt-core/app/status/TrocaDePlanoControlador.java
=> Fix paginação relatórios

influunt-api/app/controllers/UsuariosController.java, influunt-api/conf/application.conf, influunt-api/modules/influunt-core/app/checks/InfluuntValidator.java, influunt-api/modules/influunt-core/app/models/Usuario.java, influunt-api/test/models/UsuarioTest.java, influunt-app/app/views/usuarios/form.html
=> Perfil obrigatório para usuários se não for root

influunt-app/features/controladores/wizard.feature, influunt-app/features/step_definitions/controladores/wizard.steps.js, influunt-app/features/support/page-objects/wizard_controlador.js
- Cucumber para as confirmações nada a preencher
=> close #1735

influunt-api/app/controllers/ControladoresController.java, influunt-api/conf/evolutions/default/29.sql, influunt-api/modules/influunt-core/app/json/ControladorCustomDeserializer.java, influunt-api/modules/influunt-core/app/models/EstagioPlano.java, influunt-app/app/scripts/controllers/planos.js, influunt-app/features/comandos_central/comandos_central.feature, influunt-app/features/support/world.js, influunt-app/test/spec/controllers/planos.js
close #1715 
close #1731 
close #1732 
close #1710
=> Ajustes planos

influunt-api/app/controllers/ControladoresController.java, influunt-api/app/controllers/monitoramento/MonitoramentoController.java, influunt-api/app/controllers/monitoramento/StatusControladorController.java, influunt-api/app/utils/ImposicaoHelper.java, influunt-api/modules/influunt-core/app/status/StatusConexaoControlador.java, influunt-api/test/controllers/monitoramento/StatusConexaoTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/config.js, influunt-app/app/scripts/controllers/impor-config.js, influunt-app/app/views/main.html
=> Filtro controladores por online/offline

influunt-api/app/controllers/AgrupamentosController.java, influunt-api/app/controllers/ControladoresController.java, influunt-api/influunt_seed.sql, influunt-api/modules/influunt-core/app/models/Agrupamento.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/test/controllers/AgrupamentosControllerTest.java, influunt-api/test/controllers/ControladoresControllerTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/agrupamentos.js, influunt-app/app/scripts/controllers/concerns/crud.js
=> Cadastrar eventos de agrupamento

influunt-api/app/controllers/PlanosController.java, influunt-api/app/reports/PlanosReportService.java, influunt-api/app/reports/TabelaHorariaReportService.java, influunt-api/app/utils/ImposicaoHelper.java, influunt-api/modules/influunt-core/app/checks/PlanosCentralCheck.java, influunt-api/modules/influunt-core/app/models/Controlador.java, influunt-api/modules/influunt-core/app/models/Plano.java, influunt-api/modules/influunt-device/app/os72c/client/handlers/ConfiguracaoActorHandler.java, influunt-api/test/controllers/RelatoriosControllerTest.java, influunt-api/test/controllers/SubareasControllerTest.java, influunt-api/test/integracao/EnvioConfiguracaoCompletaTest.java, influunt-api/test/integracao/EnvioTabelaHorariaTest.java, influunt-api/test/integracao/ImposicoesControllerTest.java, influunt-api/test/integracao/JsonTest.java, influunt-api/test/models/ControladorPlanoTest.java, influunt-app/app/json/i18n-pt-br.json, influunt-app/app/scripts/controllers/impor-config.js, influunt-app/app/views/impor_config/index.html, influunt-app/app/views/relatorios/tabelaHoraria.html
close #1908 
close #1907 
close #1913 
close #1915
=> 1908 melhoria comandos central

influunt-app/app/index.html, influunt-app/app/json/env.json, influunt-app/app/scripts/app.js, influunt-app/app/scripts/controllers/controladores/aneis.js, influunt-app/app/scripts/controllers/controladores/dados-basicos.js, influunt-app/app/scripts/directives/helper-endereco.js, influunt-app/app/scripts/filters/nome-endereco.js, influunt-app/app/scripts/services/cet-localizacao.js, influunt-app/app/scripts/services/cte-localizacao.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html, influunt-app/bower.json, influunt-app/gulpfile.js, influunt-app/test/karma.conf.js, influunt-app/test/spec/controllers/controladores.js, influunt-app/test/spec/controllers/controladores/aneis.js, influunt-app/test/spec/controllers/controladores/dados-basicos.js, influunt-app/test/spec/filters/nome-endereco.js, influunt-app/test/spec/filters/resource-to-string.js
closes #1939 - remove google places api e add CTE places api
=> closes #1939 - remove google places api e add CET places api

influunt-app/app/scripts/directives/helper-endereco.js, influunt-app/app/views/controladores/wizard/aneis.html, influunt-app/app/views/controladores/wizard/dados-basicos.html
Algumas alterações no comportamento do helper-endereco para endereços das CTE's
=> hotfixes helper endereco

influunt-app/app/index.html, influunt-app/bower.json
Corrige warning do raven.js em produção
=> fixes raven.js warning

influunt-api/modules/influunt-central/app/CentralModule.java
Corrige o problema da Central não responder às requisições
=> Correção comandos da central

influunt-api/influunt_seed.sql
Permissões que estavam faltando para executar os comandos de central
=> Permissões da central

influunt-api/conf/application.conf, influunt-api/influunt_seed.sql, influunt-app/app/scripts/services/paho-provider.js, influunt-app/app/views/common/content_top_navigation.html, influunt-app/app/views/common/paho-disconnected-warning.html
- Adiciona um alerta de central offline no frontend
=> adiciona mensagem de alerta de central offline
